import { Geist, Geist_Mono } from "next/font/google";
import Navbar from '@/components/nav/Navbar';
import StoreProvider from '@/components/storeProvider';
import Footer from '@/components/footer/footer';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <StoreProvider>
          <Navbar />
          {children}
           <Footer />
        </StoreProvider>
      </body>
    </html>
  );
}
